export const FETCH_CREATE_TOKEN = "FETCH_CREATE_TOKEN";
export const SET_LOGIN_ROLE = "SET_LOGIN_ROLE";
export const UPDATE_IS_LOGIN_LOADING = "UPDATE_IS_LOGIN_LOADING";
export const UPDATE_IS_AUTH = "UPDATE_IS_AUTH";
export const IS_LOGIN_VALIDATION_ERROR = "IS_LOGIN_VALIDATION_ERROR";