export const FETCH_CREATE_TOKEN = "FETCH_CREATE_TOKEN";
export const SET_LOGIN_ROLE = "SET_LOGIN_ROLE";
export const SET_LOGIN_PASSWORD = "SET_LOGIN_PASSWORD";
export const UPDATE_IS_LOGIN_LOADING = "UPDATE_IS_LOGIN_LOADING";
export const UPDATE_IS_AUTH = "UPDATE_IS_AUTH";